"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[](fg:color_1)\
$directory\
[](fg:color_1 bg:color_2)\
$battery\
[](fg:color_2 bg:color_3)\
$git_branch\
$git_status\
[](fg:color_3 bg:color_4)\
$time\
[ ](fg:color_4)\
$line_break$character"""

# format = "a>"

palette = 'asexual'

[palettes.genderfluid]
color_1 = '#ff76a4'
color_2 = '#ffffff'
color_3 = '#c011d7'
color_4 = '#404040'
color_5 = '#2f3cbe'

[palettes.agender]
color_1 = '#202020'
color_2 = '#404040'
color_3 = '#b7f684'

[palettes.asexual]
color_1 = '#202020'
color_2 = '#a3a3a3'
color_3 = '#ffffff'
color_4 = '#800080'


[directory]
style = "fg:white bg:color_1"
format = "[$path ]($style)"

[battery]
format = "[ $symbol $percentage ]($style)"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 10
charging_symbol = "󰢜"
discharging_symbol = "󰁺"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 20
charging_symbol = "󰂆"
discharging_symbol = "󰁻"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 30
charging_symbol = "󰂇"
discharging_symbol = "󰁼"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 40
charging_symbol = "󰂈"
discharging_symbol = "󰁼"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 50
charging_symbol = "󰢝"
discharging_symbol = "󰁾"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 60
charging_symbol = "󰂉"
discharging_symbol = "󰁿"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 70
charging_symbol = "󰢞"
discharging_symbol = "󰂀"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 80
charging_symbol = "󰂊"
discharging_symbol = "󰂁"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 90
charging_symbol = "󰂋"
discharging_symbol = "󰂂"

[[battery.display]]
style = "bg:color_2 fg:black"
threshold = 100
charging_symbol = "󰂅"
discharging_symbol = "󰁹"

[git_branch]
symbol = ""
style = "bg:color_3"
format = '[[ $symbol $branch ](fg:black bg:color_3)]($style)'

[git_status]
style = "bg:color_3"
format = '[[($all_status$ahead_behind )](fg:black bg:color_3)]($style)'

[time]
disabled = false
time_format = "%a %-m/%-d %-I:%M%P"
style = "bg:color_4 fg:color_3"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ 󱞩](bold fg:green)'
error_symbol = '[ 󱞩](bold fg:red)'
