'$schema' = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_1)\
[$directory](fg:color_3 bg:color_1)\
[](fg:color_1 bg:color_2)\
[$battery](bg:color_2 fg:color_1)\
[](fg:color_2 bg:color_3)\
[( $git_branch$git_status )](fg:color_1 bg:color_3)\
[](fg:color_3 bg:color_4)\
[$time](fg:color_3 bg:color_4)\
[ ](fg:color_4)\
$line_break$character
"""

add_newline = false

palette = 'asexual'

[palettes.asexual]
color_1 = '#000000'
color_2 = '#a3a3a3'
color_3 = '#ffffff'
color_4 = '#800080'

[directory]
format = ' $path '

[battery]
format = ' $symbol $percentage '

[[battery.display]]
threshold = 10
charging_symbol = '󰢜'
discharging_symbol = '󰁺'

[[battery.display]]
threshold = 20
charging_symbol = '󰂆'
discharging_symbol = '󰁻'

[[battery.display]]
threshold = 30
charging_symbol = '󰂇'
discharging_symbol = '󰁼'

[[battery.display]]
threshold = 40
charging_symbol = '󰂈'
discharging_symbol = '󰁼'

[[battery.display]]
threshold = 50
charging_symbol = '󰢝'
discharging_symbol = '󰁾'

[[battery.display]]
threshold = 60
charging_symbol = '󰂉'
discharging_symbol = '󰁿'

[[battery.display]]
threshold = 70
charging_symbol = '󰢞'
discharging_symbol = '󰂀'

[[battery.display]]
threshold = 80
charging_symbol = '󰂊'
discharging_symbol = '󰂁'

[[battery.display]]
threshold = 90
charging_symbol = '󰂋'
discharging_symbol = '󰂂'

[[battery.display]]
threshold = 100
charging_symbol = '󰂅'
discharging_symbol = '󰁹'

[git_branch]
format = '$symbol $branch'
symbol = ''

[git_status]
format = '( $all_status$ahead_behind)'

[time]
format = '  $time '
time_format = '%a %-m/%-d %-I:%M%P'
disabled = false

[line_break]
disabled = false

[character]
success_symbol = '[ 󱞩](bold fg:green)'
error_symbol = '[ 󱞩](bold fg:red)'
disabled = false
