'$schema' = 'https://starship.rs/config-schema.json'

format = """
[](fg:color_1)\
[$os$username](fg:color_2 bg:color_1)\
[](fg:color_1 bg:color_2)\
[$directory](fg:color_4 bg:color_2)\
[](fg:color_2 bg:color_3)\
[$cpp$python$rust](fg:color_2 bg:color_3)\
[](fg:color_3 bg:color_4)\
[( $git_branch$git_status )](fg:color_2 bg:color_4)\
[](fg:color_4 bg:color_5)\
[$time](bg:color_5 fg:color_2)\
[](fg:color_5)\
$line_break$character
"""

add_newline = false

palette = 'genderfluid'

[palettes.genderfluid]
color_1 = '#ff76a4'
color_2 = '#ffffff'
color_3 = '#c011d7'
color_4 = '#404040'
color_5 = '#2f3cbe'

[os]
format = '$symbol'
disabled = false

[os.symbols]
EndeavourOS = ' '

[username]
format = ' $user '
show_always = true

[directory]
format = ' $path '

[cpp]
format = ' $symbol($version(-$name)) '
symbol = ' '
disabled = false

[python]
format = ' $symbol$pyenv_prefix($version)( \($virtualenv\)) '
symbol = ' '

[rust]
format = ' $symbol$version '
symbol = ' '

[git_branch]
format = '$symbol$branch'
symbol = ' '

[git_status]
format = '( $all_status$ahead_behind)'

[time]
format = '  $time '
time_format = '%a %-m/%-d %-I:%M%P'
disabled = false

[line_break]
disabled = false

[character]
success_symbol = '[ 󱞩](bold fg:green)'
error_symbol = '[ 󱞩](bold fg:red)'
disabled = false
